default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: howarts_rails_development
  username: postgres
  password: 02125019
  port: 5432

test:
  <<: *default
  database: howarts_rails_test
  username: postgres
  password: 02125019
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
